// RTMPE SDK — Runtime/Core/SpawnManager.cs
//
// Manages the lifecycle of networked objects: prefab registration,
// local instantiation/destruction, and owner-leave cleanup.
//
// Architecture notes:
//   • SpawnManager is the CENTRAL hub for object lifecycle. It owns the
//     NetworkObjectRegistry and OwnershipManager (exposed as properties).
//   • Spawn() / Despawn() create/destroy locally AND send a packet to
//     the server for relay to other clients in the room. When the server
//     relays a Spawn/Despawn to a receiving client, the NetworkManager
//     packet handler calls CreateLocal() / DestroyLocal() directly.
//   • CreateLocal() / DestroyLocal() are internal so only the SDK itself
//     (or tests via InternalsVisibleTo) can call them. These are the
//     primitives that the server-driven spawn path will invoke.
//   • OnPlayerLeftRoom() handles the DestroyWithOwner contract defined
//     on NetworkBehaviour. For objects with DestroyWithOwner=false, the
//     server is responsible for sending ownership grants — no local
//     mutation occurs here (server-authoritative ownership).
//   • ClearAll() is called on disconnect / room leave to tear down all
//     spawned objects (fires OnNetworkDespawn for each, then destroys GOs).
//   • Object IDs are generated by combining the low 32 bits of the gateway
//     session ID (shifted into the high half) with a monotonic counter
//     (low 32 bits). This ensures uniqueness across clients without
//     server coordination.

using System;
using System.Collections.Generic;
using UnityEngine;

namespace RTMPE.Core
{
    /// <summary>
    /// Manages network object spawning, prefab registration, and owner-leave cleanup.
    /// Access via <see cref="NetworkManager.Spawner"/>.
    /// All methods must be called from the Unity main thread.
    /// </summary>
    public sealed class SpawnManager
    {
        private readonly NetworkObjectRegistry _registry;
        private readonly OwnershipManager _ownership;
        private readonly NetworkManager _networkManager;

        private readonly Dictionary<uint, GameObject> _prefabs =
            new Dictionary<uint, GameObject>();

        private ulong _nextLocalId = 1;

        // ── Properties ─────────────────────────────────────────────────────────

        /// <summary>The shared object registry for all spawned objects.</summary>
        public NetworkObjectRegistry Registry => _registry;

        /// <summary>The ownership manager for server-authoritative ownership.</summary>
        public OwnershipManager Ownership => _ownership;

        // ── Constructor ────────────────────────────────────────────────────────

        /// <summary>
        /// Create a SpawnManager.
        /// </summary>
        /// <param name="registry">Shared object registry.</param>
        /// <param name="ownership">Ownership manager (created by this or externally).</param>
        /// <param name="networkManager">Active NetworkManager for ID generation and future sends.</param>
        public SpawnManager(
            NetworkObjectRegistry registry,
            OwnershipManager ownership,
            NetworkManager networkManager)
        {
            _registry       = registry       ?? throw new ArgumentNullException(nameof(registry));
            _ownership      = ownership      ?? throw new ArgumentNullException(nameof(ownership));
            _networkManager = networkManager ?? throw new ArgumentNullException(nameof(networkManager));
        }

        // ── Prefab Registration ────────────────────────────────────────────────

        /// <summary>
        /// Register a prefab for network spawning.
        /// The prefab must have a <see cref="NetworkBehaviour"/> component.
        /// Overwrites any previous registration with the same ID (logs warning).
        /// </summary>
        /// <param name="prefabId">Unique identifier for this prefab type.</param>
        /// <param name="prefab">The prefab <c>GameObject</c> to register.</param>
        public void RegisterPrefab(uint prefabId, GameObject prefab)
        {
            if (prefab == null)
                throw new ArgumentNullException(nameof(prefab));

            if (_prefabs.ContainsKey(prefabId))
                Debug.LogWarning(
                    $"[SpawnManager] RegisterPrefab: overwriting existing prefabId {prefabId}.");

            _prefabs[prefabId] = prefab;
        }

        /// <summary>
        /// Remove a prefab registration. Returns true if it was registered.
        /// </summary>
        public bool UnregisterPrefab(uint prefabId) => _prefabs.Remove(prefabId);

        /// <summary>True if a prefab is registered under <paramref name="prefabId"/>.</summary>
        public bool HasPrefab(uint prefabId) => _prefabs.ContainsKey(prefabId);

        // ── Spawn / Despawn (Public API) ───────────────────────────────────────

        /// <summary>
        /// Spawn a networked object from a registered prefab.
        ///
        /// Creates the object locally and sends a SpawnRequest to the server
        /// for relay to other clients in the room.
        /// </summary>
        /// <param name="prefabId">Registered prefab identifier.</param>
        /// <param name="position">World-space spawn position.</param>
        /// <param name="rotation">World-space spawn rotation.</param>
        /// <param name="ownerPlayerId">
        /// Room player UUID of the owner. When <see langword="null"/>,
        /// defaults to <see cref="NetworkManager.LocalPlayerStringId"/>.
        /// </param>
        /// <returns>The spawned <see cref="NetworkBehaviour"/>, or null on failure.</returns>
        public NetworkBehaviour Spawn(
            uint prefabId,
            Vector3 position,
            Quaternion rotation,
            string ownerPlayerId = null)
        {
            if (!_prefabs.ContainsKey(prefabId))
            {
                Debug.LogError($"[SpawnManager] Spawn: prefab {prefabId} is not registered.");
                return null;
            }

            var objectId = GenerateObjectId();
            var owner = ownerPlayerId
                ?? _networkManager.LocalPlayerStringId
                ?? string.Empty;

            // Send SpawnRequest to server for relay to other clients.
            SendSpawnPacket(prefabId, objectId, owner, position, rotation);

            return CreateLocal(prefabId, objectId, owner, position, rotation);
        }

        /// <summary>
        /// Despawn (destroy) a networked object.
        ///
        /// Destroys the object locally and sends a DespawnRequest to the server
        /// for relay to other clients in the room.
        /// </summary>
        /// <param name="objectId">The network object ID to despawn.</param>
        public void Despawn(ulong objectId)
        {
            // Send DespawnRequest to server for relay to other clients.
            SendDespawnPacket(objectId);

            DestroyLocal(objectId);
        }

        // ── Internal: Server-Driven Operations ─────────────────────────────────

        /// <summary>
        /// Instantiate a networked object locally from a registered prefab.
        /// Called by the inbound Spawn packet handler or by <see cref="Spawn"/>.
        /// </summary>
        /// <returns>The spawned <see cref="NetworkBehaviour"/>, or null on failure.</returns>
        internal NetworkBehaviour CreateLocal(
            uint prefabId,
            ulong objectId,
            string ownerPlayerId,
            Vector3 position,
            Quaternion rotation)
        {
            if (!_prefabs.TryGetValue(prefabId, out var prefab))
            {
                Debug.LogWarning(
                    $"[SpawnManager] CreateLocal: prefab {prefabId} not registered.");
                return null;
            }

            var go = UnityEngine.Object.Instantiate(prefab, position, rotation);
            var nb = go.GetComponent<NetworkBehaviour>();
            if (nb == null)
            {
                Debug.LogError(
                    $"[SpawnManager] CreateLocal: prefab {prefabId} has no " +
                    "NetworkBehaviour component. Destroying instantiated object.");
                UnityEngine.Object.Destroy(go);
                return null;
            }

            nb.Initialize(objectId, ownerPlayerId ?? string.Empty);
            _registry.Register(nb);
            nb.SetSpawned(true);

            return nb;
        }

        /// <summary>
        /// Destroy a networked object locally.
        /// Fires <see cref="NetworkBehaviour.OnNetworkDespawn"/>, unregisters,
        /// then destroys the <c>GameObject</c>.
        /// </summary>
        internal void DestroyLocal(ulong objectId)
        {
            var nb = _registry.Get(objectId);
            if (nb == null) return;

            nb.SetSpawned(false);
            _registry.Unregister(objectId);

            // Unity null check: the GO may have been destroyed externally.
            if (nb != null)
                UnityEngine.Object.Destroy(nb.gameObject);
        }

        // ── Owner Leave Handling ───────────────────────────────────────────────

        /// <summary>
        /// Handle a player leaving the room.
        /// Destroys all objects owned by <paramref name="playerId"/> that
        /// have <see cref="NetworkBehaviour.DestroyWithOwner"/> set to
        /// <see langword="true"/>. Objects with <c>DestroyWithOwner=false</c>
        /// are left intact — the server will send ownership grant packets
        /// to reassign them (server-authoritative).
        /// </summary>
        /// <param name="playerId">Room player UUID of the player who left.</param>
        public void OnPlayerLeftRoom(string playerId)
        {
            if (string.IsNullOrEmpty(playerId)) return;

            var owned = _ownership.GetObjectsOwnedBy(playerId);
            foreach (var obj in owned)
            {
                if (obj == null) continue;

                if (obj.DestroyWithOwner)
                {
                    // Exception isolation: continue processing remaining objects.
                    try { DestroyLocal(obj.NetworkObjectId); }
                    catch (Exception ex) { Debug.LogException(ex); }
                }
                // Non-DestroyWithOwner objects: server sends ownership grants.
                // No local mutation — server-authoritative ownership.
            }
        }

        // ── Cleanup ────────────────────────────────────────────────────────────

        /// <summary>
        /// Destroy all spawned objects and reset state.
        /// Called on room leave and disconnect.
        /// Fires <see cref="NetworkBehaviour.OnNetworkDespawn"/> for each live object,
        /// then destroys all <c>GameObject</c>s.
        /// </summary>
        public void ClearAll()
        {
            // Snapshot before clearing — we need references to Destroy GameObjects
            // (registry Clear only despawns, it does not destroy GOs).
            var snapshot = _registry.GetAll();

            // Clear registry: fires SetSpawned(false) for each live object.
            _registry.Clear();

            // Destroy the Unity GameObjects.
            foreach (var obj in snapshot)
            {
                if (obj != null)
                {
                    try { UnityEngine.Object.Destroy(obj.gameObject); }
                    catch (Exception ex) { Debug.LogException(ex); }
                }
            }

            _nextLocalId = 1;
        }

        // ── Private ────────────────────────────────────────────────────────────

        /// <summary>
        /// Generate a locally-unique object ID.
        /// High 32 bits: low 32 bits of the gateway session ID (ensures cross-client uniqueness).
        /// Low 32 bits: monotonic counter (ensures per-client uniqueness).
        /// </summary>
        private ulong GenerateObjectId()
        {
            var playerId = _networkManager.LocalPlayerId;
            return ((playerId & 0xFFFFFFFF) << 32) | (_nextLocalId++);
        }

        /// <summary>
        /// Build and send a Spawn packet through the NetworkManager.
        /// Silently skips if not connected (local-only spawn still succeeds).
        /// </summary>
        private void SendSpawnPacket(
            uint prefabId,
            ulong objectId,
            string ownerPlayerId,
            Vector3 position,
            Quaternion rotation)
        {
            if (!_networkManager.IsConnected) return;

            var payload = SpawnPacketBuilder.BuildSpawnRequest(
                prefabId, objectId, ownerPlayerId, position, rotation);
            _networkManager.Send(
                _networkManager.BuildPacket(PacketType.Spawn, PacketFlags.Reliable, payload),
                reliable: true);
        }

        /// <summary>
        /// Build and send a Despawn packet through the NetworkManager.
        /// Silently skips if not connected (local-only despawn still succeeds).
        /// </summary>
        private void SendDespawnPacket(ulong objectId)
        {
            if (!_networkManager.IsConnected) return;

            var payload = SpawnPacketBuilder.BuildDespawnRequest(objectId);
            _networkManager.Send(
                _networkManager.BuildPacket(PacketType.Despawn, PacketFlags.Reliable, payload),
                reliable: true);
        }
    }
}
