// RTMPE SDK — Runtime/Core/SpawnManager.cs
//
// Manages the lifecycle of networked objects: prefab registration,
// local instantiation/destruction, and owner-leave cleanup.
//
// Architecture notes:
//   • SpawnManager is the CENTRAL hub for object lifecycle. It owns the
//     NetworkObjectRegistry and OwnershipManager (exposed as properties).
//   • Spawn() / Despawn() create/destroy locally AND send a packet to
//     the server for relay to other clients in the room. When the server
//     relays a Spawn/Despawn to a receiving client, the NetworkManager
//     packet handler calls CreateLocal() / DestroyLocal() directly.
//   • CreateLocal() / DestroyLocal() are internal so only the SDK itself
//     (or tests via InternalsVisibleTo) can call them. These are the
//     primitives that the server-driven spawn path will invoke.
//   • OnPlayerLeftRoom() handles the DestroyWithOwner contract defined
//     on NetworkBehaviour. For objects with DestroyWithOwner=false, the
//     server is responsible for sending ownership grants — no local
//     mutation occurs here (server-authoritative ownership).
//   • ClearAll() is called on disconnect / room leave to tear down all
//     spawned objects (fires OnNetworkDespawn for each, then destroys GOs).
//   • Object IDs are generated by combining the low 32 bits of the gateway
//     session ID (shifted into the high half) with a monotonic counter
//     (low 32 bits). This ensures uniqueness across clients without
//     server coordination.

using System;
using System.Collections.Generic;
using System.Threading;
using UnityEngine;

namespace RTMPE.Core
{
    /// <summary>
    /// Manages network object spawning, prefab registration, and owner-leave cleanup.
    /// Access via <see cref="NetworkManager.Spawner"/>.
    /// All methods must be called from the Unity main thread.
    /// </summary>
    public sealed class SpawnManager
    {
        private readonly NetworkObjectRegistry _registry;
        private readonly OwnershipManager _ownership;
        private readonly NetworkManager _networkManager;

        private readonly Dictionary<uint, GameObject> _prefabs =
            new Dictionary<uint, GameObject>();

        // Remembers which prefab each spawned GameObject came from so that
        // Release() can route it back to the correct pool bucket at despawn.
        // Populated by CreateLocal; consulted (and cleared) in DestroyLocal.
        // Runtime cost is O(N_live_objects) — negligible vs the per-frame
        // registry traversal.
        private readonly Dictionary<ulong, uint> _prefabOfObject =
            new Dictionary<ulong, uint>();

        // Optional pluggable pool — null means "no pooling" (use Instantiate/Destroy).
        // Assigned via SetObjectPool; cleared via ClearObjectPool.  Main-thread only.
        private INetworkObjectPool _pool;

        // Monotonic counter for the low 32 bits of locally-generated object IDs.
        // Stored as `long` (not `ulong`) so that `Interlocked.Increment` — whose
        // public overload on .NET Standard 2.1 only accepts `ref long` — can be
        // used to guarantee thread safety.  The contract remains main-thread-only
        // for correctness of the GameObject lifecycle, but atomic increment
        // preserves uniqueness even if a third-party integration accidentally
        // calls Spawn() from a background thread.
        //
        // Starts at 0 so that the first Interlocked.Increment returns 1 — preserving
        // the historical behaviour of the previous post-increment implementation
        // (`_nextLocalId = 1` + `_nextLocalId++`).  The low 32 bits are masked at
        // use-time; values cast back to ulong are always in [1, uint.MaxValue].
        private long _nextLocalId;

        // ── Properties ─────────────────────────────────────────────────────────

        /// <summary>The shared object registry for all spawned objects.</summary>
        public NetworkObjectRegistry Registry => _registry;

        /// <summary>The ownership manager for server-authoritative ownership.</summary>
        public OwnershipManager Ownership => _ownership;

        // ── Constructor ────────────────────────────────────────────────────────

        /// <summary>
        /// Create a SpawnManager.
        /// </summary>
        /// <param name="registry">Shared object registry.</param>
        /// <param name="ownership">Ownership manager (created by this or externally).</param>
        /// <param name="networkManager">Active NetworkManager for ID generation and future sends.</param>
        public SpawnManager(
            NetworkObjectRegistry registry,
            OwnershipManager ownership,
            NetworkManager networkManager)
        {
            _registry       = registry       ?? throw new ArgumentNullException(nameof(registry));
            _ownership      = ownership      ?? throw new ArgumentNullException(nameof(ownership));
            _networkManager = networkManager ?? throw new ArgumentNullException(nameof(networkManager));
        }

        // ── Prefab Registration ────────────────────────────────────────────────

        /// <summary>
        /// Register a prefab for network spawning.
        /// The prefab must have a <see cref="NetworkBehaviour"/> component.
        /// Overwrites any previous registration with the same ID (logs warning).
        /// </summary>
        /// <param name="prefabId">Unique identifier for this prefab type.</param>
        /// <param name="prefab">The prefab <c>GameObject</c> to register.</param>
        public void RegisterPrefab(uint prefabId, GameObject prefab)
        {
            if (prefab == null)
                throw new ArgumentNullException(nameof(prefab));

            if (_prefabs.ContainsKey(prefabId))
                Debug.LogWarning(
                    $"[SpawnManager] RegisterPrefab: overwriting existing prefabId {prefabId}.");

            _prefabs[prefabId] = prefab;
        }

        /// <summary>
        /// Remove a prefab registration. Returns true if it was registered.
        /// </summary>
        public bool UnregisterPrefab(uint prefabId) => _prefabs.Remove(prefabId);

        /// <summary>True if a prefab is registered under <paramref name="prefabId"/>.</summary>
        public bool HasPrefab(uint prefabId) => _prefabs.ContainsKey(prefabId);

        // ── Pooling ────────────────────────────────────────────────────────────

        /// <summary>
        /// Install a custom <see cref="INetworkObjectPool"/>.
        /// From the next spawn onwards, <see cref="SpawnManager"/> routes every
        /// instantiate/destroy through the pool.  Pass <see langword="null"/>
        /// to restore the built-in Instantiate/Destroy path.
        /// </summary>
        /// <remarks>
        /// Swapping pools at runtime is allowed but does NOT migrate already-live
        /// objects — they will be released to whichever pool is active at despawn
        /// time.  Apps that need to migrate should despawn + respawn explicitly.
        /// </remarks>
        public void SetObjectPool(INetworkObjectPool pool) => _pool = pool;

        /// <summary>Remove any installed pool, reverting to Instantiate/Destroy.</summary>
        public void ClearObjectPool() => _pool = null;

        /// <summary>The currently-installed pool, or <see langword="null"/> when none is set.</summary>
        public INetworkObjectPool ObjectPool => _pool;

        // ── Spawn / Despawn (Public API) ───────────────────────────────────────

        /// <summary>
        /// Spawn a networked object from a registered prefab.
        ///
        /// Creates the object locally and sends a SpawnRequest to the server
        /// for relay to other clients in the room.
        /// </summary>
        /// <param name="prefabId">Registered prefab identifier.</param>
        /// <param name="position">World-space spawn position.</param>
        /// <param name="rotation">World-space spawn rotation.</param>
        /// <param name="ownerPlayerId">
        /// Room player UUID of the owner. When <see langword="null"/>,
        /// defaults to <see cref="NetworkManager.LocalPlayerStringId"/>.
        /// </param>
        /// <returns>The spawned <see cref="NetworkBehaviour"/>, or null on failure.</returns>
        public NetworkBehaviour Spawn(
            uint prefabId,
            Vector3 position,
            Quaternion rotation,
            string ownerPlayerId = null)
        {
            if (!_prefabs.ContainsKey(prefabId))
            {
                Debug.LogError($"[SpawnManager] Spawn: prefab {prefabId} is not registered.");
                return null;
            }

            var objectId = GenerateObjectId();
            var owner = ownerPlayerId
                ?? _networkManager.LocalPlayerStringId
                ?? string.Empty;

            // Send SpawnRequest to server for relay to other clients.
            SendSpawnPacket(prefabId, objectId, owner, position, rotation);

            return CreateLocal(prefabId, objectId, owner, position, rotation);
        }

        /// <summary>
        /// Despawn (destroy) a networked object.
        ///
        /// Destroys the object locally and sends a DespawnRequest to the server
        /// for relay to other clients in the room.
        /// </summary>
        /// <param name="objectId">The network object ID to despawn.</param>
        public void Despawn(ulong objectId)
        {
            // Send DespawnRequest to server for relay to other clients.
            SendDespawnPacket(objectId);

            DestroyLocal(objectId);
        }

        // ── Internal: Server-Driven Operations ─────────────────────────────────

        /// <summary>
        /// Instantiate a networked object locally from a registered prefab.
        /// Called by the inbound Spawn packet handler or by <see cref="Spawn"/>.
        /// </summary>
        /// <returns>The spawned <see cref="NetworkBehaviour"/>, or null on failure.</returns>
        internal NetworkBehaviour CreateLocal(
            uint prefabId,
            ulong objectId,
            string ownerPlayerId,
            Vector3 position,
            Quaternion rotation)
        {
            if (!_prefabs.TryGetValue(prefabId, out var prefab))
            {
                Debug.LogWarning(
                    $"[SpawnManager] CreateLocal: prefab {prefabId} not registered.");
                return null;
            }

            // Route through the pool when installed; fall back to Instantiate
            // otherwise.  A null return from a pool is a contract violation and
            // is treated as a fatal error — the surrounding game code assumes
            // Spawn produces a live object.
            GameObject go;
            if (_pool != null)
            {
                go = _pool.Acquire(prefabId, prefab, position, rotation);
                if (go == null)
                {
                    Debug.LogError(
                        $"[SpawnManager] CreateLocal: INetworkObjectPool.Acquire " +
                        $"returned null for prefabId {prefabId}. Pools MUST return " +
                        "a live GameObject. Falling back to Instantiate this time.");
                    go = UnityEngine.Object.Instantiate(prefab, position, rotation);
                }
                else
                {
                    // The pool may have handed us a cached instance whose position
                    // was set at a previous despawn.  Force both transform fields
                    // before the NetworkBehaviour wakes up so OnNetworkSpawn sees
                    // the correct pose.  Use localPosition/localRotation for safety
                    // when the pool parents instances under a reuse bucket.
                    go.transform.SetPositionAndRotation(position, rotation);
                    if (!go.activeSelf) go.SetActive(true);
                }
            }
            else
            {
                go = UnityEngine.Object.Instantiate(prefab, position, rotation);
            }

            var nb = go.GetComponent<NetworkBehaviour>();
            if (nb == null)
            {
                Debug.LogError(
                    $"[SpawnManager] CreateLocal: prefab {prefabId} has no " +
                    "NetworkBehaviour component. Destroying instantiated object.");
                // A pooled instance that lost its NetworkBehaviour somehow —
                // destroy rather than returning it to the pool to prevent a
                // corrupted instance from being reused.
                UnityEngine.Object.Destroy(go);
                return null;
            }

            nb.Initialize(objectId, ownerPlayerId ?? string.Empty);
            _registry.Register(nb);
            _prefabOfObject[objectId] = prefabId;
            nb.SetSpawned(true);

            return nb;
        }

        /// <summary>
        /// Destroy a networked object locally.
        /// Fires <see cref="NetworkBehaviour.OnNetworkDespawn"/>, unregisters,
        /// then destroys the <c>GameObject</c>.
        /// </summary>
        internal void DestroyLocal(ulong objectId)
        {
            var nb = _registry.Get(objectId);
            if (nb == null)
            {
                // Still try to clear any stale prefab mapping for this id so the
                // dictionary doesn't accumulate orphans when objects are
                // externally destroyed.
                _prefabOfObject.Remove(objectId);
                return;
            }

            nb.SetSpawned(false);
            _registry.Unregister(objectId);

            _prefabOfObject.TryGetValue(objectId, out uint prefabId);
            _prefabOfObject.Remove(objectId);

            // Unity null check: the GO may have been destroyed externally.
            if (nb == null) return;

            // When a pool is installed, return the instance for reuse instead
            // of destroying it.  The pool is responsible for deactivating the
            // GameObject — but we do a final IsOwner-safe NetworkBehaviour
            // reset so the pooled instance is in a known state next spawn.
            if (_pool != null)
            {
                try { _pool.Release(prefabId, nb.gameObject); }
                catch (Exception ex)
                {
                    Debug.LogException(ex);
                    // If the pool throws, fall back to destroy to avoid a leak.
                    UnityEngine.Object.Destroy(nb.gameObject);
                }
            }
            else
            {
                UnityEngine.Object.Destroy(nb.gameObject);
            }
        }

        // ── Late-Join Resync ───────────────────────────────────────────────────

        /// <summary>
        /// Mark every NetworkVariable on every locally-owned object as dirty
        /// so the next 30 Hz flush retransmits its current value.  Called by
        /// <see cref="NetworkManager"/> when another player joins the current
        /// room, giving the new joiner a full state snapshot within ~33 ms
        /// instead of waiting for a future value change.
        /// <para>
        /// No-op when the registry is empty or no objects are locally owned.
        /// Runs on the Unity main thread.
        /// </para>
        /// <para>
        /// Current scope: only <c>NetworkVariable</c> values participate.
        /// <c>NetworkTransform</c> already forces its next broadcast on each
        /// interpolation frame, so pose sync is naturally covered.  The
        /// trade-off of marking ALL variables (vs only unchanged ones) is a
        /// single redundant flush cycle per join — negligible at typical
        /// object counts, and far cheaper than a new protocol round trip.
        /// </para>
        /// </summary>
        public void MarkAllVariablesDirtyForResync()
        {
            var objects = _registry.GetAll();
            foreach (var nb in objects)
            {
                if (nb == null) continue;
                if (!nb.IsOwner || !nb.IsSpawned) continue;
                try { nb.MarkAllVariablesDirty(); }
                catch (Exception ex)
                {
                    // Isolate per-object failure: one misbehaving NetworkBehaviour
                    // must not block resync for the rest of the owned roster.
                    Debug.LogException(ex);
                }
            }
        }

        // ── Owner Leave Handling ───────────────────────────────────────────────

        /// <summary>
        /// Handle a player leaving the room.
        /// Destroys all objects owned by <paramref name="playerId"/> that
        /// have <see cref="NetworkBehaviour.DestroyWithOwner"/> set to
        /// <see langword="true"/>. Objects with <c>DestroyWithOwner=false</c>
        /// are left intact — the server will send ownership grant packets
        /// to reassign them (server-authoritative).
        /// </summary>
        /// <param name="playerId">Room player UUID of the player who left.</param>
        public void OnPlayerLeftRoom(string playerId)
        {
            if (string.IsNullOrEmpty(playerId)) return;

            var owned = _ownership.GetObjectsOwnedBy(playerId);
            foreach (var obj in owned)
            {
                if (obj == null) continue;

                if (obj.DestroyWithOwner)
                {
                    // Exception isolation: continue processing remaining objects.
                    try { DestroyLocal(obj.NetworkObjectId); }
                    catch (Exception ex) { Debug.LogException(ex); }
                }
                // Non-DestroyWithOwner objects: server sends ownership grants.
                // No local mutation — server-authoritative ownership.
            }
        }

        // ── Cleanup ────────────────────────────────────────────────────────────

        /// <summary>
        /// Destroy all spawned objects and reset state.
        /// Called on room leave and disconnect.
        /// Fires <see cref="NetworkBehaviour.OnNetworkDespawn"/> for each live object,
        /// then destroys all <c>GameObject</c>s.
        /// </summary>
        public void ClearAll()
        {
            // Snapshot before clearing — we need references to Destroy/Release GameObjects
            // (registry Clear only despawns, it does not destroy GOs).
            var snapshot = _registry.GetAll();

            // Copy the prefab-of-object map before the registry changes it so
            // per-object pool routing survives the Clear() sweep below.
            var prefabSnapshot = new Dictionary<ulong, uint>(_prefabOfObject);

            // Clear registry: fires SetSpawned(false) for each live object.
            _registry.Clear();

            // Destroy or release the Unity GameObjects.
            foreach (var obj in snapshot)
            {
                if (obj == null) continue;
                try
                {
                    if (_pool != null)
                    {
                        // Use the recorded prefab id when available; otherwise the
                        // pool must either route by its own bookkeeping or destroy.
                        uint prefabId = prefabSnapshot.TryGetValue(obj.NetworkObjectId, out var pid)
                            ? pid : uint.MaxValue;
                        _pool.Release(prefabId, obj.gameObject);
                    }
                    else
                    {
                        UnityEngine.Object.Destroy(obj.gameObject);
                    }
                }
                catch (Exception ex) { Debug.LogException(ex); }
            }

            _prefabOfObject.Clear();

            // Interlocked.Exchange is atomic w.r.t. concurrent Increment calls —
            // a partial read/write mid-reset cannot observe a torn 64-bit value.
            // The contract is still "reset only after ClearAll on disconnect",
            // but the atomic reset provides defence against unexpected call sites.
            Interlocked.Exchange(ref _nextLocalId, 0);
        }

        // ── Private ────────────────────────────────────────────────────────────

        /// <summary>
        /// Generate a locally-unique object ID.
        /// High 32 bits: low 32 bits of the gateway session ID (ensures cross-client uniqueness).
        /// Low 32 bits: monotonic counter (ensures per-client uniqueness).
        /// </summary>
        private ulong GenerateObjectId()
        {
            var playerId = _networkManager.LocalPlayerId;
            // Atomic post-increment equivalent:
            //   `_nextLocalId++` in the original returned N, then stored N+1.
            //   `Interlocked.Increment` returns the incremented value (N+1),
            //   so we use the RESULT as the new ID — first call returns 1,
            //   matching the historical `_nextLocalId = 1` starting value.
            ulong counter = (ulong)Interlocked.Increment(ref _nextLocalId);
            return ((playerId & 0xFFFFFFFF) << 32) | (counter & 0xFFFFFFFFUL);
        }

        /// <summary>
        /// Build and send a Spawn packet through the NetworkManager.
        /// Silently skips if not connected (local-only spawn still succeeds).
        /// </summary>
        private void SendSpawnPacket(
            uint prefabId,
            ulong objectId,
            string ownerPlayerId,
            Vector3 position,
            Quaternion rotation)
        {
            if (!_networkManager.IsConnected) return;

            var payload = SpawnPacketBuilder.BuildSpawnRequest(
                prefabId, objectId, ownerPlayerId, position, rotation);
            _networkManager.Send(
                _networkManager.BuildPacket(PacketType.Spawn, PacketFlags.Reliable, payload),
                reliable: true);
        }

        /// <summary>
        /// Build and send a Despawn packet through the NetworkManager.
        /// Silently skips if not connected (local-only despawn still succeeds).
        /// </summary>
        private void SendDespawnPacket(ulong objectId)
        {
            if (!_networkManager.IsConnected) return;

            var payload = SpawnPacketBuilder.BuildDespawnRequest(objectId);
            _networkManager.Send(
                _networkManager.BuildPacket(PacketType.Despawn, PacketFlags.Reliable, payload),
                reliable: true);
        }
    }
}
